"""
Модуль стилей для GUI компонентов.

Экспортирует все константы темы для удобного импорта.
"""

from gui.styles.theme import (
    BACKGROUND_PRIMARY,
    BACKGROUND_SECONDARY,
    BACKGROUND_TERTIARY,
    ACCENT_CYAN,
    ACCENT_CYAN_HOVER,
    ACCENT_CYAN_ACTIVE,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    TEXT_MUTED,
    BORDER_COLOR,
    BORDER_LIGHT,
    STATUS_SUCCESS,
    STATUS_ERROR,
    STATUS_WARNING,
    STATUS_INFO,
    FONT_FAMILY,
    FONT_SIZE_TITLE,
    FONT_SIZE_BODY,
    FONT_SIZE_SMALL,
    SIDEBAR_COLLAPSED_WIDTH,
    SIDEBAR_EXPANDED_WIDTH,
    SIDEBAR_ANIMATION_DURATION,
    # Glassmorphism
    GLASS_SIDEBAR_BG,
    GLASS_CARD_BG,
    GLASS_BUTTON_BG,
    GLASS_BORDER,
    GLASS_HOVER,
)

__all__ = [
    "BACKGROUND_PRIMARY",
    "BACKGROUND_SECONDARY",
    "BACKGROUND_TERTIARY",
    "ACCENT_CYAN",
    "ACCENT_CYAN_HOVER",
    "ACCENT_CYAN_ACTIVE",
    "TEXT_PRIMARY",
    "TEXT_SECONDARY",
    "TEXT_MUTED",
    "BORDER_COLOR",
    "BORDER_LIGHT",
    "STATUS_SUCCESS",
    "STATUS_ERROR",
    "STATUS_WARNING",
    "STATUS_INFO",
    "FONT_FAMILY",
    "FONT_SIZE_TITLE",
    "FONT_SIZE_BODY",
    "FONT_SIZE_SMALL",
    "SIDEBAR_COLLAPSED_WIDTH",
    "SIDEBAR_EXPANDED_WIDTH",
    "SIDEBAR_ANIMATION_DURATION",
    # Glassmorphism
    "GLASS_SIDEBAR_BG",
    "GLASS_CARD_BG",
    "GLASS_BUTTON_BG",
    "GLASS_BORDER",
    "GLASS_HOVER",
]
